### PR TITLE
Development

### PR DESCRIPTION
**Pull request by sonegillis**

### CODE REVIEW

**Comment by bellom** [comment]
#### Currently working on this PR....

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team,
Kindly be aware that after After Ruby OOP Tic Tac Toe project, you are to use `Git Flow`, you do the following; 
1 - Create a Pull Request from the feature-branch branch to the development branch.
2 - Fill and submit the code review request form.

According to Microverse guidelines, i will be dropping few things you need to update to meet up with the guideline. kindly fix the following; 
1. Leave one empty line between feature, context or describe blocks. Do not leave empty line after the last such block in a group. And space should be around symbols [checkout this article for knowledge on how to write accepted rspec test](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-between-describes)
2.  Kindly delete the empty `game.rb`

Kindly make these changes and submit another code review, :+1: await you ......

**Comment by Zibilyonik** [comment]
The change to Git Flow will take too much time now, but I will be using it in future projects.

**Comment by Zibilyonik** [comment]
I have to submit for a code review now as is since I cannot activate the stickler for my old partner's account myself. If you can, please let me know and I will try to fix as you suggest.

**Comment by bellom** [comment]
Yeah, go ahead and submit for review

**Comment by Zibilyonik** [comment]
> Yeah, go ahead and submit for review

Already have

**Comment by AdnanAfsari** [comment]
Adnan Afsari working on it

**Review by AdnanAfsari — APPROVED** [review]
Hello @sonegillis @Zibilyonik ✋ 
Nice work guys , i think you have all the changes that the previous reviewer requested to do so ita a 👍 from me :)

Happy Coding

**Pull request merged**
